"""add_cascade_delete_foreign_key

Revision ID: d9b67958c9dc
Revises: e49d130e2c49
Create Date: 2026-06-26 15:33:38.056558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9b67958c9dc'
down_revision: Union[str, Sequence[str], None] = 'e49d130e2c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uptime_logs', sa.Column('target_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'uptime_logs', 'monitoring_targets', ['target_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptime_logs', type_='foreignkey')
    op.drop_column('uptime_logs', 'target_id')
    # ### end Alembic commands ###
